version: '3.7'

services:

  db:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - DB_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGUSER=postgres
  test:
    image: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data/
    environment:
      - DB_PORT=5432
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGUSER=postgres

  redis_pr:
    image: "redis:6-alpine"
    expose:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_pr_data:/data

  app:
    build:
      context: ./app
    volumes:
      - ./app/:/app
      - app_volume:/vol/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis_pr

volumes:
  db_test:
  db_volume:
  app_volume:
  redis_pr_data: